### ISSUE TITLE
Why there's no way to change "bower_components" path from bower.json?

### ISSUE THREAD

**Issue by victorperin** [bower/json#23]
Enabling change the path of `bower_components` right from bower.json, could simplify the implementation on some projects, without the need the creation of `.bowerrc` file.

**Comment by desandro** [comment]
Thanks for your input. .bowerrc is the place for configuration for the user, `bower.json` is the property list for the package. It's best we keep these two concerns in separate places.

**Comment by victorperin** [comment]
Ok. But, if you change the .bowerrc config of an repo, it'll be necessary to change every call to the components .
I see it as a package configuration rather then an user setting.

For example:
If i use jquery as a bower component, i have to call it from `/bower_components/jquery/dist/jquery.min.js`
But, if some user change .bowerrc he'll also need to change the jquery call.
So, why this configuration must be on user configuration file? Shouldn't it be on repo config?
