### ISSUE TITLE
Missing 0.6.0 tag?

### ISSUE THREAD

**Issue by glepretre** [bower/json#34]
I think the version number [has been bumped](https://github.com/bower/json/commit/30d5868fc136beb036ff94c149d48a9cd9d67b3d) but the `0.6.0` tag has not been pushed:

![selection_002](https://cloud.githubusercontent.com/assets/5930831/12273263/2e4e5604-b965-11e5-8f63-6cd11c09d276.png)

**Comment by sheerun** [comment]
Thanks for noticing. Fixed
